// Mock data for the Inspection Module

export const mockUsers = [
  { id: "1", name: "John Doe", email: "john.doe@company.com", role: "Compliance Manager", avatar: "JD", status: "active" },
  { id: "2", name: "Sarah Chen", email: "sarah.chen@company.com", role: "Compliance Manager", avatar: "SC", status: "active" },
  { id: "3", name: "Mike Rodriguez", email: "mike.r@company.com", role: "EHS Officer", avatar: "MR", status: "active" },
  { id: "4", name: "Jennifer Walsh", email: "jennifer.w@company.com", role: "Department Head", avatar: "JW", status: "active" },
  { id: "5", name: "David Kim", email: "david.k@company.com", role: "Auditor", avatar: "DK", status: "active" },
  { id: "6", name: "John Smith", email: "john.smith@company.com", role: "Compliance Manager", avatar: "JS", status: "active" },
  { id: "7", name: "Sarah Johnson", email: "sarah.j@company.com", role: "EHS Officer", avatar: "SJ", status: "active" },
  { id: "8", name: "Mike Williams", email: "mike.w@company.com", role: "Auditor", avatar: "MW", status: "active" },
];

export const mockInspections = [
  {
    id: "INS-001",
    title: "Quarterly Safety Inspection - Building A",
    status: "IN_PROGRESS",
    severity: "HIGH",
    inspector: "Sarah Chen",
    reviewer: "Mike Rodriguez",
    dueDate: "2025-11-15",
    completionRate: 65,
    findingsCount: 3,
    site: "Headquarters",
    area: "Building A",
    template: "Safety Inspection Template",
  },
  {
    id: "INS-002",
    title: "ISO 9001 Compliance Audit",
    status: "PENDING_REVIEW_L1",
    severity: "CRITICAL",
    inspector: "John Doe",
    reviewer: "Jennifer Walsh",
    dueDate: "2025-11-10",
    completionRate: 100,
    findingsCount: 5,
    site: "Manufacturing Plant",
    area: "Production Floor",
    template: "ISO 9001 Template",
  },
  {
    id: "INS-003",
    title: "Fire Safety Equipment Check",
    status: "APPROVED",
    severity: "MEDIUM",
    inspector: "David Kim",
    reviewer: "Mike Rodriguez",
    dueDate: "2025-11-08",
    completionRate: 100,
    findingsCount: 1,
    site: "Warehouse",
    area: "Storage Area",
    template: "Fire Safety Template",
  },
  {
    id: "INS-004",
    title: "IATF 16949 Process Audit",
    status: "ASSIGNED",
    severity: "HIGH",
    inspector: "Sarah Chen",
    reviewer: "Jennifer Walsh",
    dueDate: "2025-11-20",
    completionRate: 0,
    findingsCount: 0,
    site: "Manufacturing Plant",
    area: "Assembly Line",
    template: "IATF 16949 Template",
  },
  {
    id: "INS-005",
    title: "Environmental Compliance Check",
    status: "OVERDUE",
    severity: "CRITICAL",
    inspector: "Mike Rodriguez",
    reviewer: "Jennifer Walsh",
    dueDate: "2025-11-05",
    completionRate: 45,
    findingsCount: 7,
    site: "Headquarters",
    area: "Waste Management",
    template: "Environmental Template",
  },
];

export const mockFindings = [
  {
    id: "FND-001",
    inspectionId: "INS-001",
    title: "Missing fire extinguisher in corridor",
    description: "Fire extinguisher unit FE-103 is missing from its designated location",
    severity: "HIGH",
    status: "OPEN",
    category: "Safety Equipment",
    assignedTo: "Mike Rodriguez",
    dueDate: "2025-11-18",
    evidence: ["photo1.jpg", "photo2.jpg"],
    location: "Building A, 2nd Floor Corridor",
  },
  {
    id: "FND-002",
    inspectionId: "INS-002",
    title: "Incomplete training records",
    description: "Training records for 5 employees are incomplete or outdated",
    severity: "CRITICAL",
    status: "ACTIONED",
    category: "Documentation",
    assignedTo: "Jennifer Walsh",
    dueDate: "2025-11-12",
    evidence: [],
    location: "HR Department",
    capaId: "CAPA-045",
  },
  {
    id: "FND-003",
    inspectionId: "INS-001",
    title: "Emergency exit blocked",
    description: "Emergency exit door blocked by storage boxes",
    severity: "CRITICAL",
    status: "UNDER_REVIEW",
    category: "Safety Violation",
    assignedTo: "Sarah Chen",
    dueDate: "2025-11-14",
    evidence: ["photo3.jpg"],
    location: "Building A, 1st Floor",
  },
  {
    id: "FND-004",
    inspectionId: "INS-005",
    title: "Improper waste segregation",
    description: "Hazardous waste mixed with general waste in bin W-07",
    severity: "HIGH",
    status: "PENDING_VERIFICATION",
    category: "Environmental",
    assignedTo: "David Kim",
    dueDate: "2025-11-10",
    evidence: ["photo4.jpg", "photo5.jpg"],
    location: "Waste Management Area",
    capaId: "CAPA-047",
  },
];

export const mockTemplates = [
  {
    id: "TPL-001",
    name: "Safety Inspection Template",
    status: "PUBLISHED",
    version: "2.1",
    sections: 8,
    items: 45,
    lastModified: "2025-10-15",
    createdBy: "Jennifer Walsh",
    standard: "ISO 45001",
  },
  {
    id: "TPL-002",
    name: "ISO 9001 Template",
    status: "PUBLISHED",
    version: "3.0",
    sections: 12,
    items: 67,
    lastModified: "2025-09-20",
    createdBy: "Mike Rodriguez",
    standard: "ISO 9001",
  },
  {
    id: "TPL-003",
    name: "Environmental Template",
    status: "DRAFT",
    version: "1.0",
    sections: 6,
    items: 32,
    lastModified: "2025-11-01",
    createdBy: "Sarah Chen",
    standard: "ISO 14001",
  },
  {
    id: "TPL-004",
    name: "Fire Safety Template",
    status: "PUBLISHED",
    version: "1.5",
    sections: 5,
    items: 28,
    lastModified: "2025-08-10",
    createdBy: "David Kim",
    standard: "NFPA",
  },
];

export const mockSchedules = [
  {
    id: "SCH-001",
    name: "Monthly Safety Inspections",
    frequency: "Monthly",
    nextDue: "2025-12-01",
    template: "Safety Inspection Template",
    assignedTo: "Sarah Chen",
    sites: ["Headquarters", "Manufacturing Plant"],
    status: "ACTIVE",
  },
  {
    id: "SCH-002",
    name: "Quarterly ISO Audits",
    frequency: "Quarterly",
    nextDue: "2026-02-01",
    template: "ISO 9001 Template",
    assignedTo: "John Doe",
    sites: ["Manufacturing Plant"],
    status: "ACTIVE",
  },
  {
    id: "SCH-003",
    name: "Weekly Fire Safety Checks",
    frequency: "Weekly",
    nextDue: "2025-11-18",
    template: "Fire Safety Template",
    assignedTo: "David Kim",
    sites: ["All Sites"],
    status: "ACTIVE",
  },
];

export const mockKPIs = {
  dueToday: 3,
  overdue: 2,
  openFindings: 12,
  highSeverity: 5,
  onTimePercentage: 87,
  completionTrend: [75, 82, 78, 85, 89, 87, 91, 88, 85, 89, 92, 87],
  findingsBySeverity: {
    critical: 4,
    high: 8,
    medium: 15,
    low: 23,
  },
  siteCompliance: [
    { site: "Headquarters", score: 92 },
    { site: "Manufacturing Plant", score: 85 },
    { site: "Warehouse", score: 95 },
    { site: "Office Building", score: 88 },
  ],
};

export const statusColors = {
  DRAFT: "status-draft",
  ASSIGNED: "status-assigned",
  IN_PROGRESS: "status-in-progress",
  SUBMITTED: "status-submitted",
  PENDING_REVIEW_L1: "warning",
  PENDING_REWORK: "warning",
  APPROVED_L1: "info",
  PENDING_REVIEW_L2: "warning",
  APPROVED: "status-approved",
  CLOSED: "status-closed",
  OVERDUE: "destructive",
  // Finding statuses
  OPEN: "warning",
  UNDER_REVIEW: "info",
  ACTIONED: "success",
  PENDING_VERIFICATION: "warning",
};

export const severityColors = {
  CRITICAL: "destructive",
  HIGH: "warning",
  MEDIUM: "info",
  LOW: "muted",
};
